# Generated by Django 5.0.1 on 2024-02-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_checkoutaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='country',
        ),
    ]
